final List<String> tips = [
  "Get plenty of sleep",
  "Manage stress",
  "Ask for help",
  "Connect with others and be sociable",
  "Do something you enjoy",
  "Activity and exercise",
  "Do things for others",
  "Watch for thinking traps",
  "Slowing down",
  "Solve problems"
];

final List<String> tipsDesc = [
  "Sleep is really important for our physical and mental health. Sleep helps to regulate the chemicals in our brain that transmit information.\n\nThese chemicals are important in managing our moods and emotions. If we don't get enough sleep, we can start to feel depressed or anxious.\n\nHere are some things to try if you do not sleep well:\n\nAvoid exercising too close to your bedtime. Exercise gives you energy. But slow, relaxing activities like yoga can help calm you down before bed.\n\nAvoid big meals, alcohol, cigarettes and caffeine before bed. Caffeine is the part of coffee or black tea that makes you feel awake.\n\nMake sure your room is comfortable for sleeping. Many people find that they sleep best when their room is dark, quiet and cool.\n\nStick to quiet activities just before bed, like reading.\n\nFollow a routine. Try to go to bed around the same time every night and wake up around the same time every morning, even on weekends.\n\nOnly use your bedroom for sleeping. Do work or watch TV in a different room.\n\nAvoid naps during the day if you have a hard time sleeping at night.\nAvoid sleeping pills. You may fall asleep faster, but they do not give you good, restful sleep.",  "Stress is often unavoidable, but knowing what triggers your stress and knowing how to cope is key in maintaining good mental health. Try to manage your responsibilities and worries by making a list or a schedule of when you can resolve each issue. Often if you break down your worries and stresses and write them down, you realise that they are manageable.\n\nTry to avoid burying your head in the sand, and tackle problems face on. If you find you are having trouble sleeping, or are waking up thinking about all of the things that are stressing you out, write them down and reassure yourself that you can deal with them in the morning.\n\nTo stay healthy, we need to find help when we start to feel unwell. The same is true for mental health. Mental health problems are easier to care for when they are caught quickly. If you are feeling unwell and nothing seems to help, it is important to talk to your doctor or counsellor.",
  "None of us are superhuman. We all sometimes get tired or overwhelmed by how we feel or when things don’t go to plan.\n\nIf things are getting too much for you and you feel you can’t cope, ask for help. Your family or friends may be able to offer practical help or a listening ear.\n\nIf you are struggling to feel happy, cope with everyday life, find meaning or feel connected to others, see your doctor or a mental health professional.\n\nAlmost half of peoples will experience a mental disorder at some time in their life — depression, anxiety and substance abuse are the most common disorders.",
  "There’s nothing better than catching up with someone face to face, but that’s not always possible. You can also give them a call, drop them a note, or chat to them online instead.\n\nKeep the lines of communication open: it’s good for you! Make an effort to maintain good relationships and talk to people whenever you get the chance.\n\nHaving friends is important not just for your self-esteem, but also for providing support when you're not feeling too great.\n\nResearch has found that talking to others for just ten minutes can improve memory and test scores! Having good relationships with other people is the most important factor contributing to a sense of wellbeing. This can include family, friends, workmates and others in the community.\n\nInvesting time and energy in your relationships can lead to great benefits for all involved. There are many different ways we can help each other.\n\nSome people are good at dealing with feelings. This can help us feel comforted.\n\nSome people are good at helping out, like babysitting or grocery shopping. This can help us manage day-to-day chores.\n\nSome people are good at sharing a different point of view. This can help us look at problems more realistically.\n\nSome people are good at sharing information. This can help us find better solutions.",
  "Try to make time for doing the fun things you enjoy. If you like going for a walk, painting or a specific TV show, try to set aside time to enjoy yourself. If we don't spend any time doing things we enjoy, we can become irritable and unhappy.\n\nCount your blessings. Try keeping a gratitude journal and write down 3 positive things each day. This can lead to increased wellbeing.\n\nTalking about your feelings can help you stay in good mental health and deal with times when you feel troubled. Enjoying yourself can help beat stress. Doing an activity you enjoy probably means you’re good at it, and achieving something boosts your self-esteem.",
  "Regular exercise can boost your self-esteem and can help you concentrate, sleep, and feel better. Exercise keeps the brain and your other vital organs healthy, and is also a significant benefit towards improving your mental health.\n\nActivity and exercise are essential in maintaining good mental health. Being active not only gives you a sense of achievement, but it boosts the chemicals in your brain that help put you in a good mood. Exercising can help eliminate low mood, anxiety, stress and feeling tired and lazy. It is also linked to living a longer life.\n\nYou don't need to run a marathon or play 90 minutes of football; a short walk or some another gentle activity might do the trick.",
  "Making a contribution to the community, however small, increases social wellbeing. Many people feel a sense of contributing through meaningful work, but this could also mean volunteering, helping a neighbour or performing small acts of kindness. Take some time to do the things you really enjoy.\n\nPleasant events can lead to positive emotions that can cancel out negative feelings. Helping others isn't just good for the people you're helping; it's good for you too. Helping someone can help with your self-esteem and make you feel good about your place in the world.\n\nFeeling as though you're part of a community is a really important part of your mental health. You could try volunteering for a local charity, or just being neighbourly.",
  "The way we think about something has a big effect on the way we feel. If we feel like we can handle a problem, we often feel good. If we do not think that we can handle a problem, we often feel bad.\n\nSometimes, we think that something is bad, even when it is not true. These thoughts are sometimes called “thinking traps.” They are traps because they are easy to fall into and can get us stuck and feeling bad.\n\nHere are some common thinking traps:\n\nThinking that bad things always happen to you. “I wanted to go to the beach, but now it is raining. This always happens to me! Now my day is ruined!”\n\nThinking that something can only be all good or all bad. “I did not do as well as I wanted on that last test. I am not smart enough for this course.”\n\nFocusing only on the negative part of a situation. “My team won, but I cannot believe I missed that shot. I must be very bad at soccer. Maybe I should stop playing.”\nJumping to conclusions before you know what really happened. “My friend did not call me back. She must not like me very much.”",
  "We all need to take time to slow down and relax. It is a big part of managing stress and enjoying our lives.\nWhen we do not take time to slow down, stresses can add up until we feel too overwhelmed to do anything.\n\nWhen we relax, it is easier to see problems and solutions clearly. It is easier to manage difficult feelings , and it is easier to see the good sides of things. It is easier to focus on what is happening now instead of worrying about the past or future.\n\nHow you relax is up to you. Yoga, meditation, tai chi and breathing exercises are popular activities. Other people relax by reading, doing art, exercising, spending time in nature or playing with pets. Many community centres or community groups have classes you can join. You can also learn more online or in books.",
  "We face problems every day. We can fix some problems easily, but other problems are not as easy to solve. When we do not take action, stress can build up until we do not know what to do next.\n\nThis is an easy way to tackle problems. The next time you are facing a problem, follow these steps:\n\nStep 1: Decide what the problem is. Try to be as exact as possible. It is easier to solve a problem when you know what needs to be fixed.\n\nStep 2: Think of different solutions or end goals. Think of as many as you can. Write them all down, even if they seem silly.\n\nStep 3: Pick the solution that you think will work best.\n\nStep 4: Decide what you need to do to try your solution. This is your plan. You can break your plan into smaller steps if you need to.\n\nStep 5: Put your plan into action. Remember to use your balanced thinking skills.\n\nStep 6: Look back to see if your plan worked. If it did not work, pick a different solution from your list in Step 2 and make a new plan. Keep going until you find a solution that works.",
];

final List<String> tipsimg = [
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2FGet%20plenty%20of%20sleep.jpg?alt=media&token=35e6fbb0-ad6c-40a2-a0fa-035d30f27999",
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2Fmanage%20stress.jpg?alt=media&token=ca5999e5-291d-4af5-afe0-694939230636",
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2Fask%20for%20help.jpg?alt=media&token=f9b6026f-d01e-4492-b772-7cfc243c8020",
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2Fconnect%20with%20others%20and%20be%20sociable.jpg?alt=media&token=a55cb315-b482-4e86-9625-3102671789fa",
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2FDo%20something%20you%20enjoy.jpg?alt=media&token=b56d7975-18c3-43a0-ad30-e971c7933005",
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2FActivity%20and%20exercise.jpg?alt=media&token=0054e738-e5f5-429f-9016-36b364a0a8a3",
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2FDo%20things%20for%20others.jpg?alt=media&token=dbf4c629-e92e-499d-9562-2b04a852bc9f",
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2FWatch%20for%20thinking%20traps.jpg?alt=media&token=68d1d5f3-da9c-455a-a927-e7d5a01fd4b5",
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2FSlowing%20down.jpg?alt=media&token=69ed8f2b-a6d5-4141-b7b5-3b6d16c16d16",
  "https://firebasestorage.googleapis.com/v0/b/the-mindfullness.appspot.com/o/Images%20for%20Tips%2FSolve%20problems.jpg?alt=media&token=1c99c0e7-c827-458b-9d11-4a27cae0ef76",
];